# Generated by Django 5.2.15 on 2026-06-23 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionale', '0002_rename_staff_ruolo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prodotto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_prodotto', models.CharField(max_length=120)),
                ('tipo_prodotto', models.CharField(max_length=100)),
                ('utilizza', models.ManyToManyField(related_name='prodotti', to='gestionale.serviziopulizia')),
            ],
            options={
                'verbose_name': 'Prodotto',
                'verbose_name_plural': 'Prodotti',
            },
        ),
        migrations.CreateModel(
            name='Squadra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_squadra', models.CharField(max_length=100)),
                ('zona_operativa', models.CharField(max_length=150)),
                ('composta_da', models.ManyToManyField(related_name='squadre', to='gestionale.staff')),
            ],
            options={
                'verbose_name': 'Squadra',
                'verbose_name_plural': 'Squadre',
            },
        ),
    ]
